/**
 * GeneratedQuestionLog Model
 * 
 * Tracks all questions generated by LLM for users
 * Used for:
 * - Avoiding duplicate questions in user sessions
 * - Analyzing which types of questions were effective
 * - Scoring generation quality
 */

import mongoose from 'mongoose';

const generatedQuestionLogSchema = new mongoose.Schema(
  {
    // Reference IDs
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },

    topicId: {
      type: String,
      required: true,
      index: true,
    },

    // Problem Identifier (unique slug for this question)
    problemId: {
      type: String,
      required: true,
      unique: true,
      index: true,
      trim: true,
      lowercase: true,
      description: 'Unique problem identifier (e.g., "maximum-depth-of-a-binary-tree")',
    },

    // Question Details
    problemTitle: {
      type: String,
      required: true,
      trim: true,
    },

    problemTitleNormalized: {
      type: String,
      required: true,
      index: true,
      lowercase: true,
      trim: true,
      description: 'Normalized title for deduplication',
    },

    topic: {
      type: String,
      required: true,
    },

    difficulty: {
      type: String,
      enum: ['Easy', 'Medium', 'Hard'],
      required: true,
      index: true,
    },

    primaryConceptTested: {
      type: String,
      required: true,
    },

    whyRecommended: {
      type: String,
      required: true,
      description: 'Personalized reason for recommending this question',
    },

    hints: [
      {
        type: String,
      },
    ],

    approachGuide: {
      type: String,
    },

    // ============================================================
    // LEETCODE-STYLE FUNCTION METADATA (NEW FIELDS)
    // ============================================================
    
    // Function metadata for structured execution
    functionMetadata: {
      type: mongoose.Schema.Types.Mixed,  // ✅ FIXED: Allow flexible object structure
      default: null,
      description: '{functionName: string, parameters: [{name: string, type: string}], returnType: string}',
    },

    // Starter code templates for each language
    starterCode: {
      javascript: String,
      python: String,
      java: String,
      cpp: String,
      csharp: String,
      go: String,
      rust: String,
      typescript: String,
    },

    // Code wrapper templates for execution
    wrapperTemplate: {
      javascript: String,
      python: String,
      java: String,
      cpp: String,
      csharp: String,
      go: String,
      rust: String,
      typescript: String,
    },

    // Structured test cases with visibility (CONSISTENT WITH QuestionBank)
    testCasesStructured: [
      {
        input: mongoose.Schema.Types.Mixed,  // JSON object
        expectedOutput: mongoose.Schema.Types.Mixed,  // JSON value/object
        visibility: {
          type: String,
          enum: ['public', 'hidden'],
          required: true,
        },
        _id: false,
      },
    ],

    // Problem constraints
    constraints: {
      type: String,
      description: 'Input/output constraints (e.g., "1 <= n <= 1000")',
    },

    // Full problem description / Problem Statement
    description: {
      type: String,
      description: 'Complete problem statement',
    },

    // Schema version (for future upgrades)
    schemaVersion: {
      type: Number,
      default: 2,  // Version 2 = LeetCode-style structured
      description: 'Schema version for backward compatibility',
    },

    isLegacy: {
      type: Boolean,
      default: false,
      description: 'Old format without wrapperTemplate; cannot execute',
    },

    // Generation Context
    generatedFor: {
      type: String,
      required: true,
    },

    learnerLevel: {
      type: String,
      enum: ['beginner', 'intermediate', 'advanced'],
      required: true,
    },

    // Source Information
    sourceQuestionBankId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'QuestionBank',
      description: 'Reference to QuestionBank if this was matched to an existing problem',
    },

    sourceUrl: {
      type: String,
      description: 'URL to the original problem if found',
    },

    isPaired: {
      type: Boolean,
      default: false,
      description: 'Whether this was paired with an actual QuestionBank entry',
    },

    // User Response
    userResponse: {
      attempted: {
        type: Boolean,
        default: false,
      },
      solved: {
        type: Boolean,
        default: false,
      },
      rating: {
        type: Number,
        min: 1,
        max: 5,
        description: 'User rating of question quality',
      },
      feedback: {
        type: String,
        description: 'User feedback on the question',
      },
      attemptedAt: Date,
    },

    // Generation Metadata
    generationSessionId: {
      type: String,
      index: true,
      description: 'Session ID to group questions generated together',
    },

    generationPromptHash: {
      type: String,
      description: 'Hash of the prompt used to generate this question',
    },

    geminiModelVersion: {
      type: String,
      default: 'gemini-2.5-flash',
      description: 'Which Gemini model version was used',
    },

    // Metrics
    isEffective: {
      type: Boolean,
      description: 'Marked as effective if user solved it or gave good feedback',
    },

    questionQualityScore: {
      type: Number,
      min: 0,
      max: 100,
      description: 'Internal score for question quality',
    },

    isDuplicate: {
      type: Boolean,
      default: false,
      index: true,
      description: 'Marked if this question was duplicate within user session',
    },

    duplicateOfId: {
      type: mongoose.Schema.Types.ObjectId,
      description: 'Reference to the original question if this is a duplicate',
    },

    // Admin flags
    isHidden: {
      type: Boolean,
      default: false,
      description: 'Hidden from user view if quality issues detected',
    },

    flaggedReason: {
      type: String,
      description: 'Reason for hiding/flagging',
    },
  },
  {
    timestamps: true,
    collection: 'generated_question_logs',
  }
);

// ============================================
// INDEXES FOR PERFORMANCE
// ============================================

// Composite indexes for common queries
generatedQuestionLogSchema.index({ userId: 1, topicId: 1, createdAt: -1 });
generatedQuestionLogSchema.index({ userId: 1, createdAt: -1 });
generatedQuestionLogSchema.index({ problemTitleNormalized: 1, userId: 1 });
generatedQuestionLogSchema.index({ userId: 1, isDuplicate: 1 });
generatedQuestionLogSchema.index({ generationSessionId: 1 });

// ============================================
// STATIC METHODS
// ============================================

/**
 * Check if a question was already generated for this user
 * Uses normalized title to detect duplicates
 */
generatedQuestionLogSchema.statics.checkDuplicate = function (userId, problemTitle, timeWindowMinutes = 60) {
  const normalizedTitle = problemTitle.toLowerCase().trim();
  const timeWindow = new Date(Date.now() - timeWindowMinutes * 60000);

  return this.findOne({
    userId,
    problemTitleNormalized: normalizedTitle,
    createdAt: { $gte: timeWindow },
    isDuplicate: false,
  });
};

/**
 * Get all generated questions for a user in a topic
 */
generatedQuestionLogSchema.statics.getByUserAndTopic = function (userId, topicId, limit = 20) {
  return this.find({
    userId,
    topicId,
    isDuplicate: false,
    isHidden: false,
  })
    .sort({ createdAt: -1 })
    .limit(limit)
    .populate('sourceQuestionBankId');
};

/**
 * Get effective questions (that user solved or rated well)
 */
generatedQuestionLogSchema.statics.getEffectiveQuestions = function (userId, limit = 10) {
  return this.find({
    userId,
    $or: [{ 'userResponse.solved': true }, { 'userResponse.rating': { $gte: 4 } }],
  })
    .sort({ 'userResponse.attemptedAt': -1 })
    .limit(limit);
};

/**
 * Mark questions as duplicates
 */
generatedQuestionLogSchema.statics.markDuplicates = async function (userId, topicId, ignoreIds = []) {
  const questions = await this.find({
    userId,
    topicId,
    _id: { $nin: ignoreIds },
    isDuplicate: false,
  });

  const titleMap = {};
  const updates = [];

  for (const q of questions) {
    const normalizedTitle = q.problemTitleNormalized;
    if (titleMap[normalizedTitle]) {
      // This is a duplicate
      updates.push({
        updateOne: {
          filter: { _id: q._id },
          update: {
            $set: {
              isDuplicate: true,
              duplicateOfId: titleMap[normalizedTitle],
            },
          },
        },
      });
    } else {
      titleMap[normalizedTitle] = q._id;
    }
  }

  if (updates.length > 0) {
    return await this.bulkWrite(updates);
  }
  return null;
};

/**
 * Get questions with statistics
 */
generatedQuestionLogSchema.statics.getStatistics = function (userId) {
  return this.aggregate([
    { $match: { userId, isDuplicate: false } },
    {
      $group: {
        _id: '$topicId',
        totalGenerated: { $sum: 1 },
        attempted: { $sum: { $cond: ['$userResponse.attempted', 1, 0] } },
        solved: { $sum: { $cond: ['$userResponse.solved', 1, 0] } },
        avgRating: { $avg: '$userResponse.rating' },
        difficulties: { $push: '$difficulty' },
      },
    },
    { $sort: { totalGenerated: -1 } },
  ]);
};

// Instance method to record user attempt
generatedQuestionLogSchema.methods.recordAttempt = function (solved = false, rating = null, feedback = null) {
  this.userResponse.attempted = true;
  this.userResponse.attemptedAt = new Date();
  this.userResponse.solved = solved;
  if (rating !== null) {
    this.userResponse.rating = rating;
  }
  if (feedback) {
    this.userResponse.feedback = feedback;
  }
  // Mark as effective if solved or rated 4+ stars
  this.isEffective = solved || (rating && rating >= 4);
  return this.save();
};

export default mongoose.model('GeneratedQuestionLog', generatedQuestionLogSchema);
